blank_issues_enabled: false
contact_links:
  - name: ğŸŒ IconizeFolder Official Website
    url: https://wangchujiang.com/IconizeFolder/
    about: Introduction to the IconizeFolder app on the official website!